apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-dashboard
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.example.com`)
      middlewares:
        - name: argocd-ip-allowlist
          namespace: argocd
      services:
        - name: argocd-server
          port: 80
          namespace: argocd
  tls:
    secretName: argocd-tls
